#File name: example_gui.py
#: kivy 1.8.0

ScreenManagement:
    MainScreen:
    AnotherScreen:
    ExerciseScreen:
    ListScreen:
	
<MainScreen>:
    name: "main"
    FloatLayout:
        Button:
            color: 0.41, 0.42, 0.74, 1
            text: "Welcome to BLAsT World!!"
            font_size: 65
        Button:
            color: 0, 0, 0.74, 1
            font_size: 25
            size_hint: 0.2, 0.1
            text: "Next"
            on_release: app.root.current = 'other'
            pos_hint: {"right":1, "bottom":1}


            
<AnotherScreen>:
    name: "other"
    FloatLayout:
        LoginScreen
        Button:
            color: 0,0,1,1
            font_size: 25
            size_hint: 0.2, 0.1
            text: "Next"
            on_release: app.root.current = 'exercise'
            pos_hint: {"right":1, "bottom":1}

        Button:
            color: 0,1,0,1
            font_size: 25
            size_hint: 0.2, 0.1
            text: "Go back"
            on_release: app.root.current = 'main'
            pos_hint: {"left":1, "bottom":1}

<ExerciseScreen>:
    name: "exercise"
    Button:
        text: "Start BLAsT Measurement!!"
        font_size: 50
        on_release: app.root.current = 'list'

<ListScreen>:
    name: "list"
    FloatLayout:
        Button:
            font_size: 30
            size_hint: 0.5, 0.1
            text: "Start Kinect Video"
            on_release: root.start_kinect()
            pos_hint: {"right":0.7, "top":0.7} 

        Button:
            font_size: 30
            size_hint: 0.5, 0.1
            text: "Start Rotational Measurement"
            pos_hint: {"right":0.7, "top":0.6} 

        Button:
            font_size: 30
            size_hint: 0.5, 0.1
            text: "Finger Flexion"
            pos_hint: {"right":0.7, "top":0.5} 

        Button:
            color: 0,1,0,1
            font_size: 25
            size_hint: 0.2, 0.1
            text: "Exit"
            on_release: app.Exit()
            pos_hint: {"right":1, "bottom":1} 

        Button:
            font_size: 25
            size_hint: 0.5, 0.1
            text: "Press the Spacebar to close Kinect"
            pos_hint: {"right":0.6, "bottom":1}

